- hosts: localhost
  tasks:
    - name: compare multiple environments
      EagleEye: 
         folder: infrastructure
         exclude:
           - dev
         file: tools.yml
      register: result
      become: true
       

    - debug: var=result  
